const products = [
  {
    id: 'running-shoes',
    title: 'Running Shoes',
    price: 99,
    category: 'Clothing',
    brand: 'Stride',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85',
    description: 'Lightweight running shoes with responsive cushioning and a breathable upper for everyday training.',
  },
  {
    id: 'wireless-headphones',
    title: 'Wireless Headphones',
    price: 89,
    category: 'Electronics',
    brand: 'AudioMax',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85',
    description: 'Comfortable over-ear wireless headphones with rich sound, soft ear cushions and long battery life.',
  },
  {
    id: 'backpack',
    title: 'Backpack',
    price: 129,
    category: 'Clothing',
    brand: 'UrbanCarry',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=85',
    description: 'A durable everyday backpack with padded storage for your laptop, accessories and essentials.',
  },
  {
    id: 'smartwatch',
    title: 'Smartwatch',
    price: 249,
    category: 'Electronics',
    brand: 'Pulse',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=85',
    description: 'Modern smartwatch with activity tracking, notifications and a crisp always-ready display.',
  },
  {
    id: 'sunglasses',
    title: 'Sunglasses',
    price: 149,
    category: 'Clothing',
    brand: 'Aero',
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=700&q=85',
    description: 'Classic lightweight sunglasses with UV protection and a clean everyday frame.',
  },
  {
    id: 'digital-camera',
    title: 'Digital Camera',
    price: 499,
    category: 'Electronics',
    brand: 'Lumina',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=85',
    description: 'Compact digital camera for sharp travel, portrait and everyday photography.',
  },
  {
    id: 't-shirt',
    title: 'T-shirt',
    price: 29,
    category: 'Clothing',
    brand: 'BasicCo',
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85',
    description: 'Soft cotton crew-neck T-shirt with a relaxed fit and easy everyday styling.',
  },
  {
    id: 'smartphone',
    title: 'Smartphone',
    price: 699,
    category: 'Electronics',
    brand: 'Nova',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=85',
    description: 'A premium smartphone with a vibrant display, capable camera system and all-day performance.',
  },
  {
    id: 'table-lamp',
    title: 'Table Lamp',
    price: 79,
    category: 'Home',
    brand: 'Glow',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85',
    description: 'Minimal table lamp that adds warm ambient lighting to a desk, bedside table or reading corner.',
  },
  {
    id: 'coffee-maker',
    title: 'Coffee Maker',
    price: 119,
    category: 'Home',
    brand: 'BrewLab',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=700&q=85',
    description: 'Compact coffee maker designed for quick, consistent cups at home or in the office.',
  },
  {
    id: 'desk-chair',
    title: 'Desk Chair',
    price: 199,
    category: 'Home',
    brand: 'Ergo',
    rating: 4.1,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=700&q=85',
    description: 'Supportive ergonomic chair with a breathable backrest and adjustable seating position.',
  },
  {
    id: 'hoodie',
    title: 'Classic Hoodie',
    price: 59,
    category: 'Clothing',
    brand: 'BasicCo',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85',
    description: 'Warm fleece hoodie with a classic silhouette, ribbed cuffs and a comfortable hood.',
  },
];

const categories = ['All', 'Electronics', 'Clothing', 'Home'];
const brands = ['All', ...new Set(products.map((product) => product.brand))];

export { products, categories, brands };
